In [1]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import(
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [2]:
df=pd.read_csv("../data/insurance.csv")

In [3]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
X=df.drop("charges",axis=1)
y=df["charges"]

In [5]:
X.head()

   age     sex     bmi  children smoker     region
0   19  female  27.900         0    yes  southwest
1   18    male  33.770         1     no  southeast
2   28    male  33.000         3     no  southeast
3   33    male  22.705         0     no  northwest
4   32    male  28.880         0     no  northwest

In [6]:
categorical_features=["sex","smoker","region"]
preprocessor=ColumnTransformer(
    transformers=[
        ("cat",OneHotEncoder(drop="first"),categorical_features)
    ],
    remainder="passthrough"
)

In [7]:
X_processed=preprocessor.fit_transform(X)

In [8]:
feature_names=preprocessor.get_feature_names_out()
X_processed=pd.DataFrame(
    X_processed,
    columns=feature_names
)

In [9]:
X_processed.head()

,cat__sex_male,cat__smoker_yes,cat__region_northwest,cat__region_southeast,cat__region_southwest,remainder__age,remainder__bmi,remainder__children
0,0.0,1.0,0.0,0.0,1.0,19.0,27.900,0.0
1,1.0,0.0,0.0,1.0,0.0,18.0,33.770,1.0
2,1.0,0.0,0.0,1.0,0.0,28.0,33.000,3.0
3,1.0,0.0,1.0,0.0,0.0,33.0,22.705,0.0
4,1.0,0.0,1.0,0.0,0.0,32.0,28.880,0.0

In [10]:
X_train,X_test,y_train,y_test=train_test_split(
    X_processed,
    y,
    test_size=0.2,
    random_state=42
)

In [11]:
print(X_train.shape)
print(X_test.shape)

(1070, 8)
(268, 8)

In [12]:
lr=LinearRegression()
lr.fit(X_train,y_train)
lr_pred=lr.predict(X_test)

In [13]:
lr_mae=mean_absolute_error(y_test,lr_pred)
lr_rmse=np.sqrt(mean_squared_error(y_test,lr_pred))
lr_r2=r2_score(y_test,lr_pred)

In [14]:
print("Linear Regression Results")
print("MAE:",lr_mae)
print("RMSE:",lr_rmse)
print("R² :", lr_r2)

Linear Regression Results
MAE: 4181.19447375367
RMSE: 5796.284659276277
R² : 0.783592976712072

In [15]:
dt=DecisionTreeRegressor(
    random_state=42
)
dt.fit(X_train,y_train)

DecisionTreeRegressor(random_state=42)

In [16]:
dt_pred=dt.predict(X_test)

In [17]:
dt_mae=mean_absolute_error(y_test,dt_pred)
dt_rmse=np.sqrt(mean_squared_error(y_test,dt_pred))
dt_r2=r2_score(y_test,dt_pred)

In [18]:
print("Decision Tree Results")

print("MAE :", dt_mae)

print("RMSE:", dt_rmse)

print("R² :", dt_r2)

Decision Tree Results
MAE : 3384.4735150597016
RMSE: 6861.241060936616
R² : 0.6967664183537811

In [19]:
comparison = pd.DataFrame({
    "Model": ["Linear Regression", "Decision Tree"],
    "MAE": [lr_mae, dt_mae],
    "RMSE": [lr_rmse, dt_rmse],
    "R² Score": [lr_r2, dt_r2]
})

comparison

               Model          MAE         RMSE  R² Score
0  Linear Regression  4181.194474  5796.284659  0.783593
1      Decision Tree  3384.473515  6861.241061  0.696766

In [20]:
from sklearn.ensemble import RandomForestRegressor

In [21]:
rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

In [22]:
rf.fit(X_train,y_train)

RandomForestRegressor(random_state=42)

In [23]:
rf_pred=rf.predict(X_test)

In [24]:
rf_mae=mean_absolute_error(y_test,rf_pred)
rf_rmse=np.sqrt(mean_squared_error(y_test,rf_pred))
rf_r2=r2_score(y_test,rf_pred)

In [25]:
print("Random Forest Results")

print("MAE :", rf_mae)

print("RMSE:", rf_rmse)

print("R² :", rf_r2)

Random Forest Results
MAE : 2548.01004704789
RMSE: 4578.140088572324
R² : 0.8649949247945795

In [26]:
comparison = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Decision Tree",
        "Random Forest"
    ],
    "MAE": [
        lr_mae,
        dt_mae,
        rf_mae
    ],
    "RMSE": [
        lr_rmse,
        dt_rmse,
        rf_rmse
    ],
    "R² Score": [
        lr_r2,
        dt_r2,
        rf_r2
    ]
})

comparison

               Model          MAE         RMSE  R² Score
0  Linear Regression  4181.194474  5796.284659  0.783593
1      Decision Tree  3384.473515  6861.241061  0.696766
2      Random Forest  2548.010047  4578.140089  0.864995

In [27]:
best_model=comparison.loc[comparison["R² Score"].idxmax()]
print(best_model)

Model       Random Forest
MAE           2548.010047
RMSE          4578.140089
R² Score         0.864995
Name: 2, dtype: object

In [28]:
from xgboost import XGBRegressor

In [29]:
xgb=XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=4,
    random_state=42
)

In [30]:
xgb.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [31]:
xgb_pred=xgb.predict(X_test)

In [32]:
xgb_mae=mean_absolute_error(y_test,xgb_pred)
xgb_rmse=np.sqrt(mean_squared_error(y_test,xgb_pred))
xgb_r2=r2_score(y_test,xgb_pred)
print("XGBoost Results")
print("MAE:",xgb_mae)
print("RMSE:",xgb_rmse)
print("R² :", xgb_r2)

XGBoost Results
MAE: 2413.520348248659
RMSE: 4309.346021044469
R² : 0.8803825129477736